// 预制种子卡：owner 固定为 esther（管理员），访客只读。
// 想改内容：管理员双击卡片直接改（或改这里重新部署）。

export const seedCards = [
  // ---------- 第一排：欢迎 / 投票 / 个人卡 ----------
  {
    id: 'seed-welcome',
    kind: 'seed',
    owner: 'esther',
    tpl: 'washi',
    data: {
      title: '👋 欢迎来到共享白板',
      body: '这里不是展示板，是游乐场：\n🪪 留一张你的名片（自我介绍卡）\n📸 贴一张拍立得，😆 扔个贴纸\n🗳️ 发起或参与一个投票\n🖌️ 点工具栏「涂鸦」，在白板任意角落乱画\n\n只能改/删自己创建的东西，别人的碰不得哦。',
    },
    x: 420,
    y: 140,
    w: 380,
    h: 280,
    createdAt: 0,
  },
  {
    id: 'seed-vote',
    kind: 'seed',
    owner: 'esther',
    tpl: 'vote',
    data: {
      question: '路过这里的你，今天心情如何？',
      options: [
        { text: '😆 开心', votes: [] },
        { text: '🙂 平静', votes: [] },
        { text: '🥱 想躺平', votes: [] },
        { text: '🤯 忙到飞起', votes: [] },
      ],
    },
    x: 960,
    y: 140,
    w: 300,
    h: 320,
    createdAt: 0,
  },
  {
    id: 'seed-about',
    kind: 'seed',
    owner: 'esther',
    tpl: 'profile',
    data: {
      avatar: '👩‍💻',
      name: 'ESTHER不二',
      sub: '在AI时代认真生活的女生',
      tag: '1 Person + AI = 1 Team',
      slogan: '慢慢来，比较快。',
      belief: '最会用AI的，是最知道自己想要什么的人。',
      quote: '"找到你喜欢的事，然后让它杀死你。" — Charles Bukowski',
      links: [
        { label: '📕 小红书 @ESTHER不二', href: 'https://www.xiaohongshu.com' },
        { label: '📮 联系我', href: 'mailto:esther.sjw@gmail.com' },
      ],
    },
    x: 1420,
    y: 140,
    w: 380,
    h: 430,
    createdAt: 0,
  },

  // ---------- 第二排：拍立得照片墙（caption 留白，Esther 自己写） ----------
  {
    id: 'seed-polaroid-sticker',
    kind: 'seed',
    owner: 'esther',
    tpl: 'polaroid',
    data: { image: '/esther-sticker.png', caption: '' },
    x: 420,
    y: 600,
    w: 230,
    h: 340,
    createdAt: 0,
  },
  {
    id: 'seed-polaroid-buer',
    kind: 'seed',
    owner: 'esther',
    tpl: 'polaroid',
    data: { image: '/wb-photo-buer.jpg', caption: '' },
    x: 700,
    y: 600,
    w: 230,
    h: 340,
    createdAt: 0,
  },
  {
    id: 'seed-polaroid-birthday',
    kind: 'seed',
    owner: 'esther',
    tpl: 'polaroid',
    data: { image: '/wb-photo-birthday.jpg', caption: '' },
    x: 980,
    y: 600,
    w: 230,
    h: 430,
    createdAt: 0,
  },
  {
    id: 'seed-polaroid-portrait',
    kind: 'seed',
    owner: 'esther',
    tpl: 'polaroid',
    data: { image: '/wb-photo-portrait.jpg', caption: '' },
    x: 1260,
    y: 600,
    w: 230,
    h: 380,
    createdAt: 0,
  },

  // ---------- 第三排：旧版手绘卡（默认文字，Esther 可双击调整） ----------
  {
    id: 'seed-sticky-intj',
    kind: 'seed',
    owner: 'esther',
    tpl: 'sticky',
    data: { text: 'INTJ 🧠\n安静地建造帝国' },
    x: 420,
    y: 1080,
    w: 220,
    h: 170,
    createdAt: 0,
  },
  {
    id: 'seed-sticky-agent',
    kind: 'seed',
    owner: 'esther',
    tpl: 'sticky',
    data: { text: 'Agent Native ✨\n不只是用AI，而是和AI一起活', blue: true },
    x: 680,
    y: 1080,
    w: 220,
    h: 170,
    createdAt: 0,
  },
  {
    id: 'seed-darkquote',
    kind: 'seed',
    owner: 'esther',
    tpl: 'darkquote',
    data: { text: '"找到你喜欢的事，然后让它杀死你。"', author: 'Charles Bukowski' },
    x: 940,
    y: 1080,
    w: 340,
    h: 190,
    createdAt: 0,
  },
  {
    id: 'seed-narrative',
    kind: 'seed',
    owner: 'esther',
    tpl: 'narrative',
    data: {
      text: '每一次都以为自己在走弯路，回头看才发现，都是在找同一件事——把混乱变成秩序，然后点亮其他人',
      author: 'ESTHER不二',
    },
    x: 1340,
    y: 1080,
    w: 400,
    h: 230,
    createdAt: 0,
  },
];

// 留言卡可选颜色
export const messageColors = ['#ffd166', '#ff9f9f', '#a8d8ff', '#b8f0c8', '#e6c9ff', '#ffe8a3'];
